[package]
name = "Glacier"
version = "0.0.0"
authors = ["sebastiano.gaiardelli@univr.it","pietro.turco@univr.it"]
homepage = "TODO"
license = "BSD 2"
description = "The service-oriented development framework for service-based manufacturing systems."

[lib]
name = "GlacierExample"
main = "examples/ICE/src/Main.lf"
target = "Python"
platform = "Native"

[app.properties]
fast = true

[dependencies]
